title: Obijuan
description: Probando Jekyll y el tema just-the-docs-template
theme: just-the-docs

url: https://obijuan.github.io/Learn-web-wiki/

# Quitar/poner el buscador true/false
search_enabled: true

# Poner una nota a pie de página
footer_content: "By Obijuan. Probando..."

# CAMBIAR EL COLOR DEL TEMA!!!! light/dark
color_scheme: dark

# External navigation links
nav_external_links:
  - title: FPGAwars
    url: https://fpgawars.github.io/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
