title: Obijuan
description: Página personal de Obijuan
theme: just-the-docs

url: https://obijuan.github.io/Learn-web-wiki/

# Quitar/poner el buscador true/false
search_enabled: true

# Poner una nota a pie de página
footer_content: "By Obijuan"

# CAMBIAR EL COLOR DEL TEMA!!!! light/dark
color_scheme: dark

# External navigation links
nav_external_links:
  - title: FPGAwars (Web)
    url: https://fpgawars.github.io/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

  - title: FPGAwars (Grupo)
    url: https://groups.google.com/g/fpga-wars-explorando-el-lado-libre
    hide_icon: false
    opens_in_new_tab:
